name: Bot Staging

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Bot Staging
    steps:
      - name: Trigger TriggerCD
        uses: SirJosh3917/triggercd-action@v0.1
        with:
          url: ${{ secrets.STAGING_URL }}
          nonce: ${{ secrets.STAGING_KEY }}
